-- Enable Row Level Security (RLS) is generally good practice, 
-- but for this Hackathon/MVP, we will start with basic tables.

-- 1. Table for Data Collections (Business Details)
CREATE TABLE IF NOT EXISTS business_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    cafe_name TEXT NOT NULL,
    owner_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT, -- Optional, can be linked to auth later
    city TEXT NOT NULL,
    state TEXT,
    country TEXT,
    address TEXT NOT NULL,
    landmarks TEXT,
    established TEXT, -- Storing as text for 'YYYY-MM' or date
    ownership TEXT,
    franchise_name TEXT,
    franchise_cost NUMERIC,
    working_days TEXT,
    timings TEXT,
    footfall INTEGER,
    peak_hours TEXT,
    expenses NUMERIC,
    lease NUMERIC,
    rent NUMERIC,
    sales NUMERIC,
    workers INTEGER,
    wages NUMERIC,
    profits NUMERIC,
    discount_provided BOOLEAN,
    offers_details TEXT,
    discount_percent NUMERIC,
    categories TEXT[], -- Array of text for categories
    service_types TEXT[], -- Array of text
    payment_methods TEXT[], -- Array of text
    resources JSONB -- Storing the dynamic list of resources as JSON
);

-- 2. Table for Chat Messages (Simple history)
CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    sender TEXT NOT NULL, -- 'user' or 'bot'
    text TEXT NOT NULL,
    user_id UUID -- Can link to Supabase Auth UUID if available
);

-- Policy examples (Optional - run these if you enable RLS)
-- ALTER TABLE business_details ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Enable read/write for all" ON business_details FOR ALL USING (true);
